version: '3.8'

services:
  app:
    build: .
    container_name: miniurl-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - DB_SSL_CA=${DB_SSL_CA}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_ni2vdRneTpJ7WlFNvWX
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: